#!/bin/bash
# Test whether cmpl exist or not 
test -s ../bin/cmpl; r0=$?
test -s ../bin/cmpl.exe; r1=$?

# isGurobi=1
# isCplex=1


if [ "$r0" = 0 -o "$r1" = 0 ]; then

    echo "######### start Cmpl tests ##############################"

	./test-cmpl 01_Standardmodell.cmpl -m -silent
	./test-cmpl 02_Standardmodell.cmpl -threads 4 -m -silent
	./test-cmpl 03_Primzahlen.cmpl -silent -script
	./test-cmpl 04_Threads.cmpl -silent -script
	./test-cmpl 05_Fibonacci.cmpl -silent -script
	./test-cmpl 06_SOS-Linear.cmpl -solver cbc -fm -silent
	./test-cmpl 06a_SOS-Native.cmpl -solver cplex -fm -silent
	./test-cmpl 07_Variablenprodukte.cmpl -var-prod-linear 3 -solver cbc -fm -silent
	./test-cmpl 07a_Variablenprodukte-Native.cmpl -solver cplex -fm -silent
	./test-cmpl 07_Mehrkriteriell.cmpl -m 07_Mehrkriteriell.mps -silent 
	./test-cmpl 08_SummeNegiert.cmpl -m 08_SummeNegiert.mps 
	./test-cmpl 09_Beispiel_Steglich.cmpl -ca -fm 09_Beispiel_Steglich.mps 
	./test-cmpl 10_Beispiel_Rost.cmpl -m 10_Beispiel_Rost.mps 


	./test-cmpl 22_diet.cmpl -silent 
    ./test-cmpl 23_production-mix.cmpl -silent 
    ./test-cmpl 24_test.cmpl -silent 
    ./test-cmpl 25_test_B.cmpl -silent 
    ./test-cmpl 26_transportation.cmpl -silent 
    ./test-cmpl 27_transportation_B.cmpl -silent 




	./test-cmpl 32_Standardmodell-data.cmpl -m -silent

	#eigentlich noch Indizierung mit teils freien Indizes, vorerst durch Schleife ersetzt
	./test-cmpl 33_Standardmodell-data.cmpl -m 

	#eigentlich fuer OSIL-Ausgabe, vorerst stattdessen MPS
	./test-cmpl 42_diet-data.cmpl -m -silent
 

    echo "######### Cmpl tests done  ###############################"
    
    #if [ -f cplex.log ] ; then rm cplex.log ; fi
	#if [ -f gurobi.log ] ; then rm gurobi.log ; fi
    
    
else 
	echo "CMPL does not exist in ../bin"
fi

